routes/web.php
<?php

use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminOrderController;
use App\Http\Controllers\AdminReviewController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CategoryController::class, 'index'])->name('main');

Route::middleware(['auth'])->group(function () {
    Route::middleware(['admin.check:admin'])->group(function () {
        Route::resource('admin_category', AdminCategoryController::class);
        Route::delete('admin_category/delete_img/{id}', [AdminCategoryController::class, 'deleteMedia'])->name('delete_img');
        Route::resource('admin_review', AdminReviewController::class);
        Route::resource('admin_order', AdminOrderController::class);
    });
});

Route::prefix('category')->group(function () {
    Route::get('/{slug}', [CategoryController::class, 'showCategory'])->name('category');
});

Route::prefix('order')->group(function () {
    Route::view('/', 'forms.order_form')->name('order_form');
    Route::post('/create', [OrderController::class, 'create'])->name('order.create');
});

Route::prefix('review')->group(function () {
    Route::view('/', 'forms.review_form')->name('review_form');
    Route::post('/create', [ReviewController::class, 'create'])->name('review.create');
});

Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
//use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

/**
 * Class Category
 * @property-read $main_image_url
 * @package App\Models
 */
class Category extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia, HasSlug;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'categories';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'text','slug'];

    public function getMainImageUrlAttribute()
    {
        $media_url = $this->getFirstMediaUrl();
        return $media_url ?: '/images/no-image.jpg';
    }

    public function getSecondImageUrlAttribute()
    {
        $items = $this->getMedia();
        if ($items->count() > 1) {
            return $items[1]->getUrl();
        } else {
            return '/images/no-image.jpg';
        }
    }

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->slugsShouldBeNoLongerThan(15);
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

resources/views/items_home/about.blade.php
<a id="about"></a>
<section class="home-page__about about-home">
    <div class="about-home__container ">
        <h2  class="about-home__title">Почему мы?</h2>
        <div class="about-home__row">
            <div class="about-home__column">
                <div class="about-home__item ">
                    <div class="about-home__item-container">
                        <div class="about-home__item-icon item-icon-1"></div>
                        <div class="about-home__item-title item-title-dark">профессионально</div>
                        <div class="about-home__item-subtitle item-subtitle-dark">Наши мастера обаладают
                            большим
                            опытом
                            и
                            выполняют все этапы работ в строгом соотвествии с тенологией
                        </div>
                    </div>
                </div>
                <div class="about-home__item  bg-item-dark">
                    <div class="about-home__item-container">
                        <div class="about-home__item-icon item-icon-2"></div>
                        <div class="about-home__item-title bg-item-dark">Отзывчивость</div>
                        <div class="about-home__item-subtitle">Принимаем во внимание все предпочтения
                            клиента
                        </div>
                    </div>
                </div>
            </div>
            <div class="about-home__column">
                <div class="about-home__item  bg-item-dark">
                    <div class="about-home__item-container">
                        <div class="about-home__item-icon item-icon-3"></div>
                        <div class="about-home__item-title">Использование качественных материалов</div>
                        <div class="about-home__item-subtitle">Мы пользуемся услугами проверенных
                            поставщиков
                        </div>
                    </div>
                </div>
                <div class="about-home__item ">
                    <div class="about-home__item-container">
                        <div class="about-home__item-icon item-icon-4"></div>
                        <div class="about-home__item-title item-title-dark">Жесткая привязка к срокам</div>
                        <div class="about-home__item-subtitle item-subtitle-dark">Мы выполняем все ремонтные
                            работы
                            в
                            строго оговоренное время
                        </div>
                    </div>
                    <a id="review"></a>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/items_home/calculator.blade.php
<section id="#calculator" class="page-home__calculator calculator">
    <div class="calculator__select">
        <div class="calculator__select-container">
            <h3 class="calculator__title"> расчет кровли</h3>
            <form action="" class="calculator__form">
                <div class="calculator__label">Материалы кровельного настила</div>
                <select class="calculator__input form-select" aria-label="Default select example">
                    <option style="font-size: 10px" selected="">профнастил</option>
                    <option style="font-size: 10px" value="1">Металлочерепица</option>
                    <option style="font-size: 10px" value="2">Ондулин</option>
                    <option style="font-size: 10px" value="3">Шифер</option>
                </select>
                <div class="col-auto">
                    <label for="exampleFormControlInput1"
                           class="calculator__label form-label">Ширина</label>
                    <input type="number" class="calculator__input form-control"
                           id="exampleFormControlInput1"
                           placeholder="1 метр">
                </div>
                <div class="col-auto">
                    <div class="col-auto">
                        <label for="exampleFormControlInput2"
                               class="calculator__label form-label">Длина</label>
                        <input type="number" class="calculator__input form-control"
                               id="exampleFormControlInput2"
                               placeholder="2 метра">
                    </div>
                </div>
                <button type="submit" class="btn item-info__btn">Рассчитать</button>
                <div class="calculator__result"><span>всего:</span> 9999 грн</div>
            </form>
        </div>
    </div>
    <div class="calculator__image">
        <div class="calculator__image-container">
            <h2 class="calculator__image-title">калькулятор ремонта
            </h2>
            <div class="calculator__image-bg">
                <img src="/img/home/house-calc.png" alt="">
            </div>
        </div>
    </div>
</section>

resources/views/items_home/categories.blade.php
<a id="categorys"></a>
@foreach($categories as $category)
    @if(( $category->id % 2 ) !== 0 )
        @if(( ($category->id-1) % 2 ) !== 0 )
            <section class="home-page__roofing services">
                <div class="services__container _container">
                    <div class="services__block">
                        <div class="services__item-left item-left">
                            <h2 class="right-item__title right-item__title-mob">{{ $category->title }}
                                <br> работы</h2>
                            <div class="item-left__img">
                                <img src="/img/home/03.jpg" alt="Дом">
                            </div>
                            <div class="item-left__info item-info">
                                <div class="item-info__text">{{ $category->text }} </div>
                            </div>
                            <a class="item-info__btn btn"
                               href="{{ route('category',['slug'=>$category->slug]) }}">
                                подробнее</a>
                        </div>

                        <div class="services__item-right right-item right-item-hidden">
                            <h2 class="right-item__title services-right-item__title">{{ $category->title }} <br>
                                работы
                            </h2>

                            <div class="item-right__img">
                                <img src="{{ $category->main_image_url}}" alt="Дом">
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        @else
            <section class="home-page__facade services-small">
                <div class="services__container _container">
                    <h2 class="services__title">{{ $category->title }} работы</h2>
                    <h2 class="services__title services__title-mob">
                        {{ $category->title }} <br> работы
                    </h2>
                    <div class="services__block">
                        <div class="services__item-left item-left">
                            <div class="item-left__img">
                                <img src="{{ $category->main_image_url}}" alt="Дом">
                            </div>
                        </div>

                        <div class="services__item-right right-item">
                            <div class="item-left__info item-info">
                                <div class="item-info__text">
                                    {{ $category->text }}
                                </div>
                            </div>
                            <a class="item-info__btn btn"
                               href="{{ route('category',['slug'=>$category->slug]) }}">
                                подробнее
                            </a>
                        </div>
                    </div>

                </div>
            </section>
        @endif

    @else
        @if(( ($category->id-1) % 2 ) === 0 )
            <section class="home-page__facade services-small">
                <div class="services__container _container">
                    <h2 class="services__title">{{ $category->title }} работы</h2>
                    <h2 class="services__title services__title-mob">
                        {{ $category->title }} <br> работы
                    </h2>
                    <div class="services__block">
                        <div class="services__item-left item-left">
                            <div class="item-left__img">
                                <img src="{{ $category->main_image_url}}" alt="Дом">
                            </div>
                        </div>

                        <div class="services__item-right right-item">
                            <div class="item-left__info item-info">
                                <div class="item-info__text">
                                    {{ $category->text }}
                                </div>
                            </div>
                            <a class="item-info__btn btn"
                               href="{{ route('category',['slug'=>$category->slug]) }}">
                                подробнее
                            </a>
                        </div>
                    </div>
                </div>
            </section>
        @else
            <section id="{{$category->id}}" class="home-page__roofing services">
                <div class="services__container _container">
                    <div class="services__block">
                        <div class="services__item-left item-left">
                            <h2 class="right-item__title right-item__title-mob">{{ $category->title }}
                                <br> работы</h2>
                            <div class="item-left__img">
                                <img src="{{ $category->main_image_url }}" alt="Дом">
                            </div>
                            <div class="item-left__info item-info">
                                <div class="item-info__text">{{ $category->text }} </div>
                            </div>
                            <a class="item-info__btn btn"
                               href="{{ route('category',['slug'=>$category->slug]) }}">
                                подробнее</a>
                        </div>

                        <div class="services__item-right right-item right-item-hidden">
                            <h2 class="right-item__title services-right-item__title">{{ $category->title }} <br>
                                работы
                            </h2>

                            <div class="item-right__img">
                                <img src="{{$category->second_image_url}}" alt="Дом">
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        @endif
    @endif
@endforeach

resources/views/items_home/reviews.blade.php
<section class="page-home__slider slider-home">
    <div class="slider-home__title-bg"></div>
    <div class="slider-home__container _container">
        <h2 class="slider-home__title">отзывы клинетов</h2>
        <div style="--swiper-navigation-color: #fff; --swiper-pagination-color: #fff"
             class="swiper mySwiper">
            <div class="parallax-bg" data-swiper-parallax="-23%"></div>
            <div class="swiper-wrapper">
                @foreach($reviews as $review)
                    <div class="swiper-slide">
                        <div class="swiper-slide-container">
                            <div class="subtitle" data-swiper-parallax="-200">{{$review->author}}</div>
                            <div class="text" data-swiper-parallax="-100">
                                <p>{{$review->message}}</p>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-pagination"></div>
        </div>
    </div>
</section>
<section><h3 class="review"><a href="{{ route('review_form') }}">Оставить отзыв</a></h3></section>