routes/web.php
<?php

use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminOrderController;
use App\Http\Controllers\AdminReviewController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CategoryController::class, 'index'])->name('main');

Route::middleware(['auth'])->group(function () {
    Route::middleware(['admin.check:admin'])->group(function () {
        Route::resource('admin_category', AdminCategoryController::class);
        Route::delete('admin_category/delete_img/{id}', [AdminCategoryController::class, 'deleteMedia'])->name('delete_img');
        Route::resource('admin_review', AdminReviewController::class);
        Route::resource('admin_order', AdminOrderController::class);
    });
});

Route::prefix('category')->group(function () {
    Route::get('/{slug}', [CategoryController::class, 'showCategory'])->name('category');
});

Route::prefix('order')->group(function () {
    Route::view('/', 'forms.order_form')->name('order_form');
    Route::post('/create', [OrderController::class, 'create'])->name('order.create');
});

Route::prefix('review')->group(function () {
    Route::view('/', 'forms.review_form')->name('review_form');
    Route::post('/create', [ReviewController::class, 'create'])->name('review.create');
});

Auth::routes();

app/Http/Controllers/AdminReviewController.php
<?php

namespace App\Http\Controllers;

use App\Models\Review;
use App\Http\Requests\ReviewRequest;
use App\Http\Requests\ReviewEditRequest;

class AdminReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_review.index', [
            'reviews' => Review::paginate(8)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_review.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReviewRequest $request)
    {
        $review = Review::create(
            $request->all()
        );
        return redirect(route('admin_review.index'))->with('status', 'Комментарий "' . $review->id . '" добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Review::changeStatus($id);
        return redirect(route('admin_review.index'))
            ->with('status', 'Комментарий '.$id.' "' . Review::find($id)->status .'"');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin_review.edit',
            ['review' => Review::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(ReviewEditRequest $request, $id)
    {
        Review::updateData($id, $request->except(['_token','_method']));
        return redirect()
            ->route('admin_review.index')
            ->with('status', 'Отзыв "' . $id . '" изменён');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Review::destroy($id);
        return redirect(route('admin_review.index'))
            ->with('status', 'Комментарий "'.$id.'" удалён');
    }
}

resources/views/admin_review/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,regular,500,600,700,800,900"
          rel="stylesheet"/>

    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"/>
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/app.css">
    <title>Отставить отзыв</title>
</head>

<body>
<div class="wrapper">
    <form action="{{ route('admin_review.store') }}" method="post" class="form__order-service order-service">
        @csrf
        <div class="order-service__container _container">
            <div class="form">
                <div class="form__title">Оставить отзыв</div>
                <div class="form__item">
                    <label for="formName" class="form__label">Имя*</label>
                    <input id="formName" type="text" name="author" value="{{old('author')}}"
                           class="form__input _req form-control {{ $errors->has('author') ? 'is-invalid' : '' }}">
                    @if($errors->has('author'))
                        <div class="invalid-feedback">
                            <strong>Напишите имя</strong>
                        </div>
                    @endif

                </div>
                <div class="form__item">
                    <label for="formMessage" class="form__label">Сообщние</label>
                    <textarea value="{{old('message')}}" maxlength="500" name="message" id="formMessage"
                    class="form__input"></textarea>
                    @if($errors->has('message'))
                        <div class="invalid-feedback">
                            <strong>Напишите комментарий</strong>
                        </div>
                    @endif
                </div>
                <button type="submit" class="form__button btn">Отправить</button>
            </div>
        </div>
    </form>
</div>

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<script type="text/javascript" src="/js/app.js"></script>
</body>

</html>

resources/views/admin_review/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Изменить отзыв</h3>
                </div>
                <form method="POST" action="{{ route('admin_review.update',["admin_review"=>$review->id]) }}">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        {{--author--}}
                        <div class="form-group">
                            <label for="exampleInputTtitle">Название категории</label>
                            <input type="text" class="form-control @error('author') is-invalid @enderror"
                                   value="{{ old('title') ?? $review->author }}"
                                   name="author" id="exampleInputTitle"
                                   placeholder="название работы">
                            @error('author')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        {{--text--}}
                        <div class="form-group">
                            <label for="exampleInputText">Описание работы</label>
                            <textarea type="text" class="form-control @error('message') is-invalid @enderror"
                                    name="message" id="exampleInputText"
                                   placeholder="описание работы">value="{{ old('text')?? $review->message}}"</textarea>
                            @error('message')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

resources/views/admin_review/index.blade.php
@extends('adminlte::page')

@section('content')

    <div class="row">
        @if (session('status'))
            <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                    <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                </symbol>
            </svg>
            <div class="alert alert-success d-flex align-items-center ml-2" role="alert">
                <svg class="bi flex-shrink-0 mr-3 me-2" width="24" height="24" role="img" aria-label="Success:">
                    <use
                        xlink:href="#check-circle-fill"/>
                </svg>
                <div>
                    {{ session('status') }}
                </div>
            </div>
        @endif
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Список комментариев</h3>
                </div>
                <div class="card-body">
                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6"></div>
                            <div class="col-sm-12 col-md-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table-striped table table-bordered table-hover dataTable"
                                       role="grid"
                                       aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th>Id</th>
                                        <th>Автор</th>
                                        <th>Комментарий</th>
                                        <th>Статус</th>
                                        <th>Действие</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($reviews as $review)
                                        <tr role="row">
                                            <td>{{$review->id}}</td>
                                            <td>{{$review->author}}</td>
                                            <td>{{$review->message}}</td>
                                            <td>
                                                <form method="get"
                                                      action="{{ route('admin_review.show',
                                                      ['admin_review'=>$review->id]) }}"
                                                      role="form"
                                                class="d-flex p-2 bd-highlight">
                                                    @csrf
                                                    @if( $review->status == "Активный")
                                                        <input class="mt-2 btn btn-block btn-outline-success btn-sm"
                                                               type="submit"
                                                               value="{{ $review->status }}">
                                                    @else
                                                        <input class="mt-2 btn btn-block btn-outline-secondary btn-sm"
                                                               type="submit"
                                                               value="{{ $review->status }}">
                                                    @endif
                                                </form>
                                            </td>
                                            <td>
                                                <a href="{{ route('admin_review.edit',
                                                      ['admin_review'=>$review->id] )}}"
                                                   type="button"
                                                   class="btn btn-block btn-outline-info btn-sm">Изменить</a>
                                                <form action="{{ route('admin_review.destroy',
                                                      ['admin_review'=>$review->id] )}}"
                                                      method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <input class="mt-2 btn btn-block btn-outline-danger btn-sm" name="delete"
                                                           type="submit"
                                                           value="Удалить">
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th rowspan="1" colspan="1">Id</th>
                                        <th rowspan="1" colspan="1">Автор</th>
                                        <th rowspan="1" colspan="1">Комментарий</th>
                                        <th rowspan="1" colspan="1">Статус</th>
                                        <th rowspan="1" colspan="1">Удалить</th>
                                    </tr>
                                    </tfoot>
                                </table>
                                {{ $reviews->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

{{--@section('js')--}}
{{--    <script>--}}
{{--        $(function () {--}}
{{--            $('#example2').DataTable({--}}
{{--                "paging": true,--}}
{{--                "lengthChange": false,--}}
{{--                "searching": true,--}}
{{--                "ordering": true,--}}
{{--                "info": true,--}}
{{--                "autoWidth": false,--}}
{{--            });--}}
{{--        });--}}
{{--    </script>--}}
{{--@endsection--}}