routes/web.php
<?php

use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminOrderController;
use App\Http\Controllers\AdminReviewController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CategoryController::class, 'index'])->name('main');

Route::middleware(['auth'])->group(function () {
    Route::middleware(['admin.check:admin'])->group(function () {
        Route::resource('admin_category', AdminCategoryController::class);
        Route::delete('admin_category/delete_img/{id}', [AdminCategoryController::class, 'deleteMedia'])->name('delete_img');
        Route::resource('admin_review', AdminReviewController::class);
        Route::resource('admin_order', AdminOrderController::class);
    });
});

Route::prefix('category')->group(function () {
    Route::get('/{slug}', [CategoryController::class, 'showCategory'])->name('category');
});

Route::prefix('order')->group(function () {
    Route::view('/', 'forms.order_form')->name('order_form');
    Route::post('/create', [OrderController::class, 'create'])->name('order.create');
});

Route::prefix('review')->group(function () {
    Route::view('/', 'forms.review_form')->name('review_form');
    Route::post('/create', [ReviewController::class, 'create'])->name('review.create');
});

Auth::routes();

app/Http/Controllers/AdminOrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use App\Http\Requests\OrderRequestst;

class AdminOrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('admin_order.index', [
            'orders' => Order::paginate(8)
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Order::destroy($id);
        return redirect(route('admin_order.index'))
            ->with('status', 'Заказ удалён');
    }
}

resources/views/admin_order/index.blade.php
@extends('adminlte::page')

@section('content')

    <div class="row">
        @if (session('status'))
            <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                    <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                </symbol>
            </svg>
            <div class="alert alert-success d-flex align-items-center ml-2" role="alert">
                <svg class="bi flex-shrink-0 mr-3 me-2" width="24" height="24" role="img" aria-label="Success:">
                    <use
                        xlink:href="#check-circle-fill"/>
                </svg>
                <div>
                    {{ session('status') }}
                </div>
            </div>
        @endif
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Список заказов</h3>
                </div>
                <div class="card-body">
                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6"></div>
                            <div class="col-sm-12 col-md-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table-striped table table-bordered table-hover dataTable"
                                       role="grid"
                                       aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th>Id</th>
                                        <th>Имя</th>
                                        <th>Телефон</th>
                                        <th>Сообщение</th>
                                        <th>Удалить</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($orders as $order)
                                        <tr role="row">
                                            <td>{{$order->id}}</td>
                                            <td>{{$order->name}}</td>
                                            <td>{{$order->phone}}</td>
                                            <td>{{$order->message}}</td>
                                            <td>
                                                <form action="{{ route('admin_order.destroy',
                                                      ['admin_order'=>$order->id] )}}"
                                                      method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <input class="mt-2 btn btn-block btn-outline-danger btn-sm"
                                                           name="delete"
                                                           type="submit"
                                                           value="Удалить">
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                        </tbody>
                                    <tfoot>
                                    <tr>
                                        <th rowspan="1" colspan="1">Id</th>
                                        <th rowspan="1" colspan="1">Автор</th>
                                        <th rowspan="1" colspan="1">Комментарий</th>
                                        <th rowspan="1" colspan="1">Статус</th>
                                        <th rowspan="1" colspan="1">Удалить</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            {{ $orders->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

{{--@section('js')--}}
{{--    <script>--}}
{{--        $(function () {--}}
{{--            $('#example2').DataTable({--}}
{{--                "paging": true,--}}
{{--                "lengthChange": false,--}}
{{--                "searching": true,--}}
{{--                "ordering": true,--}}
{{--                "info": true,--}}
{{--                "autoWidth": false,--}}
{{--            });--}}
{{--        });--}}
{{--    </script>--}}
{{--@endsection--}}