routes/web.php
<?php

use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminOrderController;
use App\Http\Controllers\AdminReviewController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CategoryController::class, 'index'])->name('main');

Route::middleware(['auth'])->group(function () {
    Route::middleware(['admin.check:admin'])->group(function () {
        Route::resource('admin_category', AdminCategoryController::class);
        Route::delete('admin_category/delete_img/{id}', [AdminCategoryController::class, 'deleteMedia'])->name('delete_img');
        Route::resource('admin_review', AdminReviewController::class);
        Route::resource('admin_order', AdminOrderController::class);
    });
});

Route::prefix('category')->group(function () {
    Route::get('/{slug}', [CategoryController::class, 'showCategory'])->name('category');
});

Route::prefix('order')->group(function () {
    Route::view('/', 'forms.order_form')->name('order_form');
    Route::post('/create', [OrderController::class, 'create'])->name('order.create');
});

Route::prefix('review')->group(function () {
    Route::view('/', 'forms.review_form')->name('review_form');
    Route::post('/create', [ReviewController::class, 'create'])->name('review.create');
});

Auth::routes();

app/Http/Controllers/AdminCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Http\Requests\CategoryAddRequest;
use App\Http\Requests\CategoryEditRequest;
use Illuminate\Support\Facades\Auth;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class AdminCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_category.index', [
            'categories' => Category::paginate(6)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\CategoryAddRequest $request
     * @return \App\Http\Requests\CategoryAddRequest
     */
    public function store(CategoryAddRequest $request)
    {
        $category = new Category();
        $category->fill($request->only(['title', 'text']));
        $category->save();

        if ($request->hasFile('img')) {
            foreach ($request->file('img') as $imgFile) {
                $category->addMedia($imgFile)->toMediaCollection();
            }
        }
        return redirect(route('admin_category.index'))->with('status', 'Категория "' . $request->title . '" добавлена');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('admin_category.edit', [
            'category' => $category,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\CategoryEditRequest $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryEditRequest $request, $id)
    {
        /**
         * @var Category $category
         */
        $category = Category::find($id);
        $category->fill($request->only(['title', 'text']));
        $category->save();

        if ($request->hasFile('img')) {
            foreach ($request->file('img') as $imgFile) {
                $category->addMedia($imgFile)->toMediaCollection();
            }
        }

        return redirect()
            ->route('admin_category.edit', $id)
            ->with('status', 'Категория "' . $request->title . '" изменина'
            );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroy($id);
        return back()
            ->with('status', 'Категория "' . $id . '" удалена');
    }

    public function deleteMedia($id)
    {
        Media::destroy($id);
        return back()->with('status', 'Картинка удалена');
    }
}

resources/views/admin_category/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Добавить новую категорию</h3>
                </div>
                <!-- form start -->
                <form enctype="multipart/form-data"
                      method="POST" action="{{ route('admin_category.store') }}">
                    @csrf
                    <div class="card-body">
                        {{--title--}}
                        <div class="form-group">
                            <label for="exampleInputTitle">Название категории</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror"
                                   value="{{ old('title') }}" name="title" id="exampleInputTitle"
                                   placeholder="название работы">
                            @error('title')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        {{--text--}}
                        <div class="form-group">
                            <label for="exampleInputText">Описание работы</label>
                            <input type="text" class="form-control @error('text') is-invalid @enderror"
                                   value="{{ old('text') }}" name="text" id="exampleInputText"
                                   placeholder="описание работы">
                            @error('text')
                            <br>
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        {{-- add img --}}
                        <div class="form-group">
                            <label>Добавить изображение</label>
                            <br>
                            <input type="file" name="img[]" multiple accept=".jpg,.png,.jpeg">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin_category/edit.blade.php
@extends('adminlte::page')

@section('content')
    <section class="content">
        <!-- Default box -->
        <div class="card-body">
            <div class="row">
                <div class="col-12 col-sm-6">
                    <div class="row">
                        @foreach($category->getMedia() as $media)
                            <div class="product-image-thumb col-6 col-sm-3 mt-3 position-relative">
                                <img  src="{{$media->getUrl()}}" alt="{{ $category->title }}">
                                <form class="position-absolute top-0 end-0"
                                      data-placement="top" title="Удалить"
                                      action="{{ route('delete_img',$media->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-secondary"
                                            type="submit">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                                             fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path
                                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                            <path fill-rule="evenodd"
                                                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                        </svg>
                                    </button>
                                </form>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="col-12 col-sm-6">
                    <h3 class="my-3">Изменить категорию "{{ $category->title }} работы"</h3>
                    <hr>
                    <!-- form  title and text-->
                    <form method="POST"
                          enctype="multipart/form-data"
                          action="{{ route('admin_category.update',["admin_category"=>$category->id]) }}">
                        @csrf
                        @method('PUT')
                        <div class="card-arrow">
                            {{--title--}}
                            <div class="form-group">
                                <label for="exampleInputTitle">Название категории</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror"
                                       value="{{ old('title') ?? $category->title }}"
                                       name="title" id="exampleInputTitle"
                                       placeholder="название работы">
                                @error('title')
                                <br>
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            {{--text--}}
                            <div class="form-group">
                                <label for="exampleInputText">Описание работы</label>
                                <textarea type="text" name="text"
                                          class="form-control @error('text') is-invalid @enderror"
                                          value="{{ old('text')?? $category->text}}"
                                          id="exampleInputText"
                                          placeholder="описание работы">{{ old('text')?? $category->text}}</textarea>
                                @error('text')
                                <br>
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <div class="form-group mt-4">
                                <label>Добавить изображение</label>
                                <div>
                                    <input type="file" name="img[]" multiple accept=".jpg,.png,.jpeg">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>

                    <hr>
                    <div class="form-group">
                        <a class="btn btn-primary" href="{{ route('admin_category.index') }}">Назад</a>
                    </div>
                    {{---------------------}}
                    {{--                        <div class="btn btn-default btn-lg btn-flat">--}}
                    {{--                            <i class="fas fa-heart fa-lg mr-2"></i>--}}
                    {{--                            Add to Wishlist--}}
                    {{--                        </div>--}}
                    {{--                    </div>--}}
                    {{---------------------}}

                </div>
            </div>
            <div class="row mt-4">
            </div>
        </div>
        <!-- /.card-body -->
    </section>
@endsection

resources/views/admin_category/index.blade.php
@extends('adminlte::page')

@section('content')

    <div class="row">
        @if (session('status'))
            <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                    <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                </symbol>
            </svg>
            <div class="alert alert-success d-flex align-items-center ml-2" role="alert">
                <svg class="bi flex-shrink-0 mr-3 me-2" width="24" height="24" role="img" aria-label="Success:">
                    <use
                        xlink:href="#check-circle-fill"/>
                </svg>
                <div>
                    {{ session('status') }}
                </div>
            </div>
        @endif
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Список категорий работ</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6"></div>
                            <div class="col-sm-12 col-md-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table-striped table table-bordered table-hover dataTable"
                                       role="grid"
                                       aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th>Id</th>
                                        <th>Название работы (категория)</th>
                                        <th>Описание</th>
                                        <th>Действие</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($categories as $category)
                                        <tr role="row">
                                            <td>{{$category->id}}</td>
                                            <td>{{$category->title}}</td>
                                            <td>{{$category->text}}</td>
                                            <td>
                                                <a type="button" class="btn btn-block btn-outline-info"
                                                   href="{{ route('admin_category.edit',
                                                   ['admin_category'=>$category->id]) }}">изменить
                                                </a>
                                                <form class="btn-block"
                                                      action="{{ route('admin_category.destroy',
                                                      ['admin_category'=>$category->id] )}}"
                                                      method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <input class="btn btn-block btn-outline-danger" name="delete"
                                                           type="submit"
                                                           value="удалить">
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th rowspan="1" colspan="1">Id</th>
                                        <th rowspan="1" colspan="1">Название работы (категория)</th>
                                        <th rowspan="1" colspan="1">Описание</th>
                                        <th rowspan="1" colspan="1">Действие</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            {{ $categories->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
{{--@section('js')--}}
{{--    <script>--}}
{{--        $(function () {--}}
{{--            $('#example2').DataTable({--}}
{{--                "paging": true,--}}
{{--                "lengthChange": false,--}}
{{--                "searching": true,--}}
{{--                "ordering": true,--}}
{{--                "info": true,--}}
{{--                "autoWidth": false,--}}
{{--            });--}}
{{--        });--}}
{{--    </script>--}}
{{--@endsection--}}